version: "3"

services:
    Frontend:
        container_name: frontend
        image: goweb:v1
        restart: always
        build: ./Frontend 
        ports:
            - "3900:3900"
        volumes:
            - ./Frontend:/usr/src/app/Frontend
    python-server:
        container_name: pythonserver
        build: ./PythonServer
        ports:
            - "3000:3000"
        volumes:
            - ./PythonServer:/usr/src/app/PythonServer
        links: 
            - graphviz
    js-server:
        container_name: jsserver
        build: ./JSServer
        ports:
            - "3200:3200"
        volumes:
            - ./JSServer:/usr/src/app/JSServer
        links: 
            - graphviz
    graphviz:
        container_name: graphviz
        image: pipalacademy/graphviz-web
        ports:
            - "3300:3300"
